### ISSUE TITLE
sreg_hdl.txt fails convert.py

### ISSUE THREAD

**Issue by mayagokhale** [anikau31/systemc-clang#49]
Using the latest master branch, I manually ran convert.py on sreg_hdl.txt (in examples/llnl-examples). It fails in the parsing phase with unexpected token at line 20 of sreg_hdl.txt. 
Probably not worth fixing since we're waiting on the new convert.py, but just FYI.

python ../../plugins/xlat/convert.py sreg_hdl.txt 
WARNING:root:Shift/reduce conflict for terminal HVARDECL:  (resolving as shift)
WARNING:root: * Reduce: <expression : hliteral>
WARNING:root: * Shift: {<hvardecl : HVARDECL * ID NOLIST>}
WARNING:root:Shift/reduce conflict for terminal HLITERAL:  (resolving as shift)
WARNING:root: * Reduce: <expression : hliteral>
WARNING:root: * Shift: {<hliteral : HLITERAL * ID NOLIST>}
Traceback (most recent call last):
  File "/Users/gokhale2/anaconda3/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 62, in get_action
    return states[state][token.type]
KeyError: 'HNOOP'
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../plugins/xlat/convert.py", line 535, in <module>
    main()
  File "../../plugins/xlat/convert.py", line 526, in main
    t = l.parse(file_content)
  File "/Users/gokhale2/anaconda3/lib/python3.7/site-packages/lark/lark.py", line 311, in parse
    return self.parser.parse(text, start=start)
  File "/Users/gokhale2/anaconda3/lib/python3.7/site-packages/lark/parser_frontends.py", line 89, in parse
    return self._parse(token_stream, start, *[sps] if sps is not NotImplemented else [])
  File "/Users/gokhale2/anaconda3/lib/python3.7/site-packages/lark/parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
  File "/Users/gokhale2/anaconda3/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 36, in parse
    return self.parser.parse(*args)
  File "/Users/gokhale2/anaconda3/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 86, in parse
    action, arg = get_action(token)
  File "/Users/gokhale2/anaconda3/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 65, in get_action
    raise UnexpectedToken(token, expected, state=state)
lark.exceptions.UnexpectedToken: Unexpected token Token(HNOOP, 'hNoop') at line 20, column 13.
Expected one of: 
	* HVARREF

**Comment by mayagokhale** [comment]
testing script and tests have changed drastically. Might as well close this issue.
